2024.11.24 11:44

diff --git a/.github/workflows/openwrt-builder.yml b/.github/workflows/openwrt-builder.yml
--- a/.github/workflows/openwrt-builder.yml
+++ b/.github/workflows/openwrt-builder.yml
@@ -98,5 +98,20 @@ jobs:
           # 获取 path 字段
           path=$(jq -r '.path' <<< "${firmware_json_object}")
           
-          echo "name:${name}"
-          echo "path:${path}"
+          if [ -z "${name}" ] || [ -z "${path}" ]; then
+              echo "Get Firmware information is Failed, please check!"
+              exit 1
+          fi
+          
+          # 设置输出
+          echo "name=${name}" >> $GITHUB_OUTPUT
+          echo "path=${path}" >> $GITHUB_OUTPUT
+          
+      - name: Upload Firmware Folder
+        uses: actions/upload-artifact@main
+        if: !cancelled() &&
+            steps.extract_firmware_info.outputs.name != '' &&
+            steps.extract_firmware_info.outputs.path != ''
+        with:
+          name: ${{ steps.extract_firmware_info.outputs.name }}
+          path: ${{ steps.extract_firmware_info.outputs.path }}
